version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - progresDB:/var/lib/zoeaubertme/postgress/data
    env_file:
      - ./.env
volumes:
  progresDB:
