pub mod silly_names_commands;
pub mod update_all_data_command;
pub mod about_text_commands;
pub mod blog_posts_commands;
pub mod micro_posts_commands;
pub mod mastodon_posts_commands;
pub mod lego_commands;
pub mod games_commands;
pub mod update_derived_data_command;
