version: 2
jobs:
  checkout_and_deps:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  qa:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn qa

  build:
      docker:
        - image: circleci/node:7.10
      working_directory: ~/repo

      steps:
        - restore_cache:
            key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
        - run: yarn build

        - save_cache:
              paths:
                - public
              key: v1-build-{{ .Environment.CIRCLE_SHA1 }}

  deploy_stage:
    docker:
      - image: wilson208/circleci-awscli
    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-build-{{ .Environment.CIRCLE_SHA1 }}

      - run:
          name: Deploy
          command: aws s3 sync ~/public s3://stage.zoeaubert.me/ --delete

workflows:
  version: 2
  build:
    jobs:
      - checkout_and_deps
      - qa:
          requires:
            - checkout_and_deps
      - build:
          requires:
            - checkout_and_deps
      - deploy_stage:
          requires:
            - qa
            - build
          filters:
            branches:
              only: develop
