version: 2
jobs:
  checkout_and_deps:
    docker:
      - image: circleci/node:10.5
    working_directory: ~/repo
    steps:
      - checkout
      - save_cache:
          paths:
            - ~/repo
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

  qa:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run qa

  build_and_deploy_stage:
    docker:
      - image: circleci/node:10.5
    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build

      - run:
          name: Update apt-get
          command: sudo apt-get update

      - run:
          name: Install python
          command: sudo apt-get install python-pip python-dev jq

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Deploy
          command: aws s3 sync public s3://stage.zoeaubert.me/ --delete

  build_and_deploy_prod:
    docker:
      - image: circleci/node:10.5
    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build

      - run:
          name: Update apt-get
          command: sudo apt-get update

      - run:
          name: Install python
          command: sudo apt-get install python-pip python-dev jq

      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Deploy
          command: aws s3 sync public s3://zoeaubert.me/ --delete

workflows:
  version: 2
  build:
    jobs:
      - checkout_and_deps
      - qa:
          requires:
            - checkout_and_deps
      - build_and_deploy_stage:
          requires:
            - qa
          filters:
            branches:
              only: develop
      - build_and_deploy_prod:
          requires:
            - qa
          filters:
            branches:
              only: master
