module.exports = [
    // {
    //     name: 'MicroBlog',
    //     target: '_blank',
    //     rel: '',
    //     url: 'https://geekyaubergine.com',
    // },
    {
        name: 'Blog',
        target: '',
        rel: '',
        url: '/blog',
    },
    {
        name: 'Timeline',
        target: '',
        rel: '',
        url: '/timeline',
    },
    {
        name: 'Photos',
        target: '',
        rel: '',
        url: '/photos',
    },
    // {
    //     name: 'Albums',
    //     target: '',
    //     rel: '',
    //     url: '/albums',
    // },
    { name: 'Hobbies', target: '', rel: '', url: '/hobbies' },
    {
        name: 'Tags',
        target: '',
        rel: '',
        url: '/tags',
    },
    // {
    //     name: 'micros',
    //     target: '',
    //     rel: '',
    //     url: '/micros',
    // },
    {
        name: '/now',
        target: '',
        rel: '',
        url: '/now',
    },
    {
        name: 'faq',
        target: '',
        rel: '',
        url: '/faq',
    },
    {
        name: 'RSS',
        target: '',
        rel: '',
        url: '/subscribe',
    },
    // {
    //     name: 'categories',
    //     target: '',
    //     rel: '',
    //     url: '/categories',
    // },
    // {
    //     name: 'links',
    //     target: '',
    //     rel: '',
    //     url: '/links',
    // },
]
