name: cli

on:
    push:
        branches: ['main']
        paths:
            - 'cli/**'
            - 'Cargo.toml'
            - 'Cargo.lock'
    pull_request:
        paths:
            - 'cli/**'
            - 'Cargo.toml'
            - 'Cargo.lock'

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install protobuf
              run: |
                  sudo apt update && sudo apt upgrade -y
                  sudo apt install -y protobuf-compiler libprotobuf-dev

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v2.0
              with:
                  envkey_API_TOKEN: ${{ secrets.API_TOKEN }}
                  envkey_WEBSERVER_URL: http://zoeaubert.me
                  envkey_GRPC_URL: http://zoeaubert.me:50051

            - name: Install rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: Check
              run: cargo check -p cli
            - name: Run tests
              run: cargo test -p cli
