name: cli

on:
    push:
        branches: ['main']
        # paths:
        #     - 'webserver/**'
        #     - 'Cargo.toml'
        #     - 'Cargo.lock'
    pull_request:
        # paths:
        #     - 'webserver/**'
        #     - 'Cargo.toml'
        #     - 'Cargo.lock'

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Make envfile
              uses: SpicyPizza/create-envfile@v2.0
              with:
                  envkey_API_TOKEN: ${{ secrets.API_TOKEN }}
                  envkey_WEBSERVER_URL: http://zoeaubert.me

            - name: Install rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
                  components: rustfmt, clippy

            - name: Install node
              uses: actions/setup-node@v4
              with:
                  node-version: '19'

            - name: Node dependencies
              run: npm install

            - name: Build
              run: cargo check -p cli
            - name: Run tests
              run: cargo test -p cli
