name: Rust

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest 1.78.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.78.0
          override: true
          components: rustfmt, clippy

      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check