name: Rust

on:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '19'
        
      - name: Node dependencies
        run: npm install

      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check